# Arquivo de configuração de patrocínio do GitHub
# Descomente e configure as opções desejadas

# GitHub Sponsors
github: johnnyvaz

# Patreon
patreon: johnnyvaz

# Buy Me a Coffee
buy_me_a_coffee: johnnyvaz

# Ko-fi
ko_fi: johnnyvaz

# PIX (para brasileiros - adicione no README)
# custom: ["https://link-para-seu-pix"]

# Open Collective
# open_collective: seu_projeto

# Liberapay
# liberapay: johnnyvaz

# PayPal
# custom: ["https://paypal.me/johnnyvaz"]
