# Arquivo de configuração de patrocínio do GitHub
# Descomente e configure as opções desejadas

# GitHub Sponsors
github: johnnyvaz

# Buy Me a Coffee
buy_me_a_coffee: johnnyvaz

# PIX (para brasileiros)
custom: ["https://johnnyvaz.com.br/pix"]

# Open Collective
# open_collective: seu_projeto

# Liberapay
# liberapay: johnnyvaz

# PayPal
# custom: ["https://paypal.me/johnnyvaz"]
